version: '3'

volumes:
  test_db_data:

services:
  rest:
    build: .
    image: aiopypay
    tty: true
    volumes:
      - ./aiopypay:/srv/aiopypay
      - ./tests:/srv/tests
    env_file:
      - ./.env
    environment:
      - WAIT_HOSTS=${POSTGRES_HOST}:${POSTGRES_PORT}
    command: /bin/bash -c "
      waitc &&
      pytest --disable-warnings -v
      "

  postgres:
    image: postgres:11.5
    tty: true
    restart: always
    env_file:
      - ./.env
    volumes:
        - test_db_data:/var/lib/postgresql/data

